name: "🫀 Keep Cache Alive"

on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:

jobs:
  keep-alive:
    name: "🫀 Touch All Caches"
    runs-on: ubuntu-latest

    steps:
      - name: "♻️ Touch arsenal"
        uses: actions/cache/restore@v6
        with:
          path: |
            ~/ccache-bin
            ~/ak3-cache
            ~/kernel-cache
            ~/.apt-cache
          key: arsenal-__keepalive__
          restore-keys: arsenal-

      - name: "♻️ Touch clang caches"
        uses: actions/cache/restore@v6
        with:
          path: ~/clang-cache
          key: clang-__keepalive__
          restore-keys: clang-
