name: "🔥 Cache Warming"
run-name: "${{ inputs.kernel_version }} | ${{ inputs.build_system }}"

on:
  workflow_dispatch:
    inputs:
      build_system:
        description: "Build System"
        type: choice
        default: "Kleaf - AOSP"
        options:
          - "Kleaf - AOSP"
          - "Make - Cirrus"
          - "Make - Neutron"
          - "Make - WeebX"
          - "Make - Zyc"
      kernel_version:
        description: "Kernel Version"
        type: choice
        default: "6.1"
        options:
          - "5.10"
          - "5.15"
          - "6.1"
          - "6.6"
          - "6.12"
      vanilla:
        description: "VANILLA"
        type: boolean
        default: true
      resukisu:
        description: "ReSukiSU"
        type: boolean
        default: false
      sukisu:
        description: "SukiSU-Ultra"
        type: boolean
        default: false
      susfs:
        description: "SuSFS"
        type: choice
        default: "enable"
        options:
          - "enable"
          - "disable"
      update_arsenal:
        description: "Update Arsenal"
        type: choice
        default: "no"
        options:
          - "yes"
          - "no"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Luminaire:
    uses: ./.github/workflows/_kernel-build.yml
    with:
      build_system:   ${{ inputs.build_system }}
      vanilla:        ${{ inputs.vanilla }}
      resukisu:       ${{ inputs.resukisu }}
      sukisu:         ${{ inputs.sukisu }}
      susfs:          ${{ inputs.susfs == 'enable' }}
      kernel_version: ${{ inputs.kernel_version }}
      update_arsenal: ${{ inputs.update_arsenal }}
      warming_mode:   "true"
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
